FROM alpine:latest

RUN apk add --no-cache python3 py3-pip git

ADD source /app/source

RUN mkdir -p /autograder/submission

RUN python3 -m pip install --break-system-package -r /app/source/requirements.txt 

WORKDIR app
