assignment_name=""
semester=""

[config]
    impl_to_use=""
    autograder_version=""

    test_directory="./student_tests"

    enforce_submission_limit=false
    submission_limit=3

    take_highest=true

    allow_extra_credit=false
    perfect_score=0
    max_score=0


[config.python]
    # Python spefic configuration

    # All extra packages need to be under a header like this.
    # This is TOML weird-ness :(
    [[extra_packages]]
        name=""
        version=""
    
[config.c]
    # c/c-like config
    use_makefile = true

    # Only supporting makefiles for now.

    # the name that we expect to exist after running the makefile
    clean_target = "clean"
    submission_name = ""



[build]

    # Things that need to be considered when building
    use_starter_code=false
    use_data_files=false
    
    allow_private=true

    build_student=true

    build_gradescope=true
    build_prarielean=true

    student_work_folder="student_work"
